### PR TITLE
Add add_files function.

### PR DESCRIPTION
**Pull request by maciekbanas**
@kalimu you will find here simple `add_files()` function. 

- Architecture of function goes for the time being with two separate parameters: `file_paths` and `file_types`.  We can think of making one `files` parameter if you find it more appropriate.
- I do not also check for any prerequisites to run the function (maybe they are necessary?)

### CODE REVIEW

**Comment by kalimu** [comment]
> @kalimu you will find here simple `add_files()` function.
> 
> * Architecture of function goes for the time being with two separate parameters: `file_paths` and `file_types`.  We can think of making one `files` parameter if you find it more appropriate.

Thanks Maciej. Can we talk more why this distinction is necessary? file_path vs file_type? Couldn't be just a single file pattern?
If I remember correctly GitStats doesn't need this distinction right?

> * I do not also check for any prerequisites to run the function (maybe they are necessary?)

Let's focus now on bare minimum, and see how it works. Once we have more stable interface we can easily add some checks.

**Comment by maciekbanas** [comment]
@kalimu the distinction is for efficiency gains:
- `file_paths` can be directly put into `get_files_content()` function,
- `file_types` must be initially put into `get_files_structure()` and only then the output can be pulled with `get_files_content()` which takes a bit longer.

If you decide to simplify it, that is ok, but then the `file_paths` (like "README.md") will be treated as `file_types` and will be first searched via `get_files_structure()` which: 
1) will take longer 
2) can result in pulling some nested, not necessary desired files.

GitStats does not necessarily need it but the distinction makes best of it. We can also make one parameter (e.g. `files`) and make GitAI code distinct it further to `file type` or `file path`.

Give me your feedback in which direction we go :)

**Comment by kalimu** [comment]
Ah, now it's clear to me! Let's leave it as it is then.
(That's why its good to have a `GitStats` expert onboard for such projects...)

**Review by kalimu — APPROVED** [review]
Haven't tested, but all looks good to me. Feel free to merge it Maciej.

**Pull request merged**
